/* options.h */
#define BAD_OPTION (-1)
#define OPT_HELP 0
#define OPT_QUIET 1
#define OPT_PICKY 2
#define OPT_TOLERANT 3
#define OPT_NEWONLY 4
#define OPT_OLDONLY 5
#define OPT_BOTH 6
#define OPT_MONO 7
#define OPT_STEREO 8
#define OPT_VERBOSE 9
#define OPT_FREQUENCY 10
#define OPT_OVERSAMPLE 11
#define OPT_TRANSPOSE 12
#define OPT_REPEATS 13
#define OPT_SPEED 14
#define OPT_MIX 15
#define OPT_START 16
#define OPT_CUT 17
#define OPT_ADD 18
#define OPT_SHOW 19
#define OPT_SYNC 20
#define OPT_SPEAKER 21
#define OPT_VOLUME 22
#define OPT_LOOP 23
#define OPT_SPEEDMODE 24
#define OPT_COLOR 25
#define OPT_HALF 26
#define OPT_DOUBLE 27
#define OPT_BW 28
#define OPT_XTERM 29
#define OPT_NOXTERM 30
#define OPT_RANDOM 31
