.Dd $Mdocdate$
.Dt TRACKER 1
.Os
.Sh NAME
.Nm tracker
.Nd play amiga protracker modules
.Sh SYNOPSIS
.Nm tracker
.Op Fl help
.Op Fl picky
.Op Fl tolerant
.Op Fl mono
.Op Fl stereo
.Op Fl verbose
.Op Fl repeats Ar count
.Op Fl loop
.Op Fl speed Ar speed
.Op Fl mix Ar percent
.Op Fl new Ns | Ns Fl old Ns | Ns Fl both
.Op Fl frequency Ar freq
.Op Fl oversample Ar times
.Op Fl transpose Ar n
.Op Fl scroll
.Op Fl color
.Op Fl sync
.Op Fl randomize
.Bk -words
.Ar file ...
.Ek
.Sh DESCRIPTION
.Nm
plays soundtracker or protracker modules.
Options are as follows
.Sh AUTHOR
Marc Espie
